'use client';
import {stockConfig} from '@/lib/watchlist.mjs';
import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,ReferenceLine,LineChart,Line,CartesianGrid} from 'recharts';
import {ArrowUpRight,TrendingUp,Activity,Flag,Layers2} from 'lucide-react';
import {stocks,sources} from '@/lib/research';
import snapshot from '@/lib/market-snapshot.json';
import {PriceTrend} from '@/components/trend-charts';
const n=(v:number|null|undefined,d=2)=>typeof v!=='number'||!Number.isFinite(v)?'不適用／待確認':v.toLocaleString('zh-TW',{maximumFractionDigits:d});
type Stock=typeof stocks[number];
const get=(id:string)=>snapshot.stocks.find(s=>s.id===id)!;
export function Quote({s,choose}:{s:Stock;choose?:()=>void}){const data=get(s.id),first=data.quoteHistory[0],last=data.quoteHistory.at(-1)!;return <article className={'quote-card quote-v2 stock-'+s.id}><div className="quote-top"><span className={'monogram '+stockConfig(s.id).theme}>{stockConfig(s.id).symbol}</span><div><h2>{s.name}<small>{s.english}</small></h2><p>{s.id}.TW · {s.business}</p></div>{choose&&<button aria-label={'閱讀'+s.name+'分析'} className="arrow-button" onClick={choose}><ArrowUpRight size={21}/></button>}</div><div className="quote-market"><div><span className="quote-label">收盤價 · {data.quote.tradingDate}</span><div className="price"><strong>{n(s.price)}</strong><small>TWD</small></div><span className={'quote-change '+(s.change>0?'rise':'fall')}>{s.change>0?'+':''}{n(s.change)} <b>{s.change>0?'+':''}{n(s.changePct)}%</b></span></div></div><div className="metrics"><div><span>本益比</span><b className={s.pe===null?'metric-unavailable':''}>{s.pe===null?'不適用':n(s.pe)}{s.pe!==null&&<small> 倍</small>}</b></div><div><span>股價淨值比</span><b>{n(s.pb)}<small> 倍</small></b></div><div><span>現金殖利率</span><b>{n(s.yield)}<small> %</small></b></div></div><p className="verdict"><i/>{s.verdict}</p><PriceTrend id={s.id}/><p className="quote-source"><a className="cite" target="_blank" rel="noreferrer" href={data.quote.source.url}>證交所收盤行情 ↗</a> · <a className="cite" target="_blank" rel="noreferrer" href={data.quote.valuationSource.url}>官方估值 ↗</a></p></article>}
export function QuarterOverview({stockId}:{stockId?:string}){const list=snapshot.stocks.filter(s=>!stockId||s.id===stockId);return <section className={'quarter-overview '+(stockId?'single':'')}><div className="quarter-heading"><span className="eyebrow">OPERATING PROGRESS</span><h2>把營運改善，拆成單季看。</h2><p>單季營業利益 · 新台幣百萬元</p></div>{list.map(s=>{const qs=s.quarters.map(q=>({...q,profitMillion:q.operatingProfit/1000,margin:('grossMarginPctReported' in q&&typeof q.grossMarginPctReported==='number')?q.grossMarginPctReported:q.grossProfit/q.revenue*100}));const latest=qs.at(-1)!;return <article className={'quarter-card stock-'+s.id} key={s.id}><div className="quarter-card-top"><span className={'company-tag '+stockConfig(s.id).theme}>{s.id} {s.name}</span><span>{latest.period}</span></div><div className="quarter-number"><strong>{latest.profitMillion>0?'+':''}{n(latest.profitMillion,s.id==='2426'?2:0)}</strong><span>百萬元<small>單季營業利益</small></span></div><div className="quarter-chart" role="img" aria-label={qs.map(q=>`${q.period}營業利益${n(q.profitMillion)}百萬元`).join('；')}><ResponsiveContainer width="100%" height={148}><BarChart data={qs} margin={{top:14,right:3,left:-24,bottom:0}}><CartesianGrid vertical={false} stroke="#e8edf6"/><XAxis dataKey="period" axisLine={false} tickLine={false} tick={{fontSize:12,fill:'#6a7a90'}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:12,fill:'#8190a4'}}/><ReferenceLine y={0} stroke="#9aaac1"/><Tooltip cursor={{fill:'#eaf0fa'}} formatter={(v)=>[`${n(Number(v))} 百萬元`,'營業利益']} contentStyle={{fontSize:14,borderRadius:8}}/><Bar dataKey="profitMillion" fill={stockConfig(s.id).accent} radius={[4,4,0,0]} maxBarSize={32} isAnimationActive={false}/></BarChart></ResponsiveContainer></div><div className="quarter-margins"><span>毛利率</span>{qs.map(q=><span key={q.period}><small>{q.period}</small><b>{n(q.margin)}%</b></span>)}</div><p className="quarter-condition"><Flag size={16}/>{s.id==='2426'?(qs.length<3?'毛利率趨勢：待確認':qs.slice(-3).every((q,i,a)=>i===0||q.margin>a[i-1].margin)?'毛利率連續兩季改善：成立':'毛利率連續兩季改善：未成立'):(qs.length<2?'連續本業獲利：待確認':qs.slice(-2).every(q=>q.operatingProfit>0)?'連續兩季本業獲利：成立':'連續兩季本業獲利：未成立')}</p><details className="quarter-source"><summary>數據口徑與來源</summary><p>{stockConfig(s.id).quarterMethod}</p>{qs.flatMap(q=>q.sources.map(source=>({url:source.url,label:source.label}))).filter((x,i,a)=>a.findIndex(y=>y.url===x.url)===i).map(source=><a target="_blank" rel="noreferrer" href={source.url} key={source.url}>{source.label} ↗</a>)}</details></article>})}</section>}
export function CompanyBrief({s}:{s:Stock}){return <section className={'company-brief stock-'+s.id}><div><span className="eyebrow">RESEARCH FILE / {s.id}</span><h2>{s.headline}</h2><p>{s.thesis}</p><div className="brief-tags"><span><Layers2 size={15}/>2026 上半年財報</span><span><Activity size={15}/>中長期基本面</span><span><TrendingUp size={15}/>估值與條件追蹤</span></div></div><aside><span>研究主軸</span><h3>{s.takeawayTitle}</h3><p>{s.takeaway}</p></aside></section>}
