'use client';
import {stockConfig} from '@/lib/watchlist.mjs';
import {ArrowRight,ArrowUpRight,ScanLine,CheckCheck,History,SlidersHorizontal,FileClock} from 'lucide-react';
import data from '@/lib/changes.json';
type Source={label?:string;url:string};
type Event={id:string;stockId:string;stock:string;item:string;before:string;after:string;period:string;reason:string;classification:string;sources:Source[];impact:{status:string;reason:string}};
type Check={stockId:string;stock:string;item:string;status:string;detail:string;sources:Source[]};
type Day={asOf:string;checkedAt:string;status:string;baselineDate:string|null;events:Event[];checks:Check[]};
const archive=data as unknown as {today:Day;history:Day[]};
function EventCard({event:e}:{event:Event}){return <article className="change-event"><div className="change-event-head"><span className={'company-tag '+stockConfig(e.stockId).theme}>{e.stock} {e.stockId}</span><h3>{e.item}</h3><small>{e.classification}</small></div><div className="change-values"><div><span>前值</span><b>{e.before}</b></div><ArrowRight size={20}/><div><span>新值</span><b>{e.after}</b></div><div><span>資料期間</span><b>{e.period}</b></div></div><p className="change-reason"><b>觸發原因</b>{e.reason}</p><div className="change-impact"><b>研究判斷：{e.impact.status}</b><p>{e.impact.reason}</p></div><div className="change-sources">{e.sources.filter((s,i,a)=>a.findIndex(o=>o.url===s.url)===i).map(s=><a href={s.url} key={s.url} target="_blank" rel="noreferrer">{s.label||'官方來源'}<ArrowUpRight size={14}/></a>)}</div></article>}
export default function ImportantChanges({stockId='all'}:{stockId?:string}){const day=archive.today,filter=(id:string)=>stockId==='all'||id===stockId;const events=day.events.filter(e=>filter(e.stockId)),pending=day.checks.filter(c=>filter(c.stockId)&&c.status==='pending'),verified=day.checks.filter(c=>filter(c.stockId)&&c.status==='verified');const settings=data.today.settings;
return <section className="important-changes panel" id="changes"><div className="section-title"><div><span className="eyebrow">DAILY INTELLIGENCE</span><h2><ScanLine size={23}/>今日重要變化</h2></div><span className="period">查核 {day.asOf}</span></div><div className="change-summary"><span><CheckCheck size={17}/>{verified.length} 項已核對</span><span><FileClock size={17}/>{pending.length} 項待確認</span><span>對照基準 {day.baselineDate||'首次建立'}</span></div>{events.length?<div className="change-events">{events.map(e=><EventCard key={e.id} event={e}/>)}</div>:<div className={'change-empty '+(pending.length?'pending':'complete')}><span><ScanLine size={26}/></span><div><h3>{pending.length?'尚無已確認的新觸發，部分項目待確認':'今日無新增重要變化'}</h3><p>{pending.length?'待確認項目不視為沒有變化；舊公告與已成立的條件也不會因補登而重新提醒。':'本次已完成資料核對，沒有新增達到提醒門檻的項目。'}</p></div></div>}
{pending.length>0&&<details className="pending-checks"><summary>查看 {pending.length} 項待確認內容</summary><div>{pending.map((c,i)=><article key={i}><b>{c.stock} · {c.item}</b><p>{c.detail}</p>{c.sources.map(s=><a href={s.url} key={s.url} target="_blank" rel="noreferrer">{s.label||'來源'} ↗</a>)}</article>)}</div></details>}
<div className="change-tools"><details><summary><SlidersHorizontal size={17}/>目前提醒門檻</summary><ul><li>單日價格漲跌幅絕對值 ≥ {settings.price.absoluteDailyChangePct}%。</li><li>月營收年增率上穿 {settings.monthlyRevenue.upwardYoyThresholdPct}%、由非負轉負，或較前月變動 ≥ {settings.monthlyRevenue.absoluteYoyChangePercentagePoints} 個百分點。</li><li>單季營業利益轉盈／轉虧；鼎元毛利率連續 {settings.quarterly.tyntekMarginImprovementQuarters} 季改善，富采與友達連續 {settings.quarterly.auoOperatingProfitPositiveQuarters} 季本業獲利。</li><li>公司事件區分官方事實、公司展望與研究推論；相同公告及持續成立的條件不重複提醒。</li></ul></details><details><summary><History size={17}/>歷史變化紀錄（{archive.history.length} 日）</summary><div className="change-history">{archive.history.map(day=><details key={day.asOf}><summary>{day.asOf} · {day.events.filter(e=>filter(e.stockId)).length} 項重要變化{day.checks.some(c=>filter(c.stockId)&&c.status==='pending')?' · 含待確認項目':''}</summary>{day.events.filter(e=>filter(e.stockId)).length?day.events.filter(e=>filter(e.stockId)).map(e=><EventCard key={e.id} event={e}/>):<p>{day.checks.some(c=>filter(c.stockId)&&c.status==='pending')?'本日沒有已確認的新觸發，部分項目待確認。':'今日無新增重要變化'}</p>}</details>)}</div></details></div></section>}
