'use client';
import {useEffect,useState} from 'react';
import {BellRing,ShieldAlert,ArrowUpRight,Clock3} from 'lucide-react';
import {Alert,AlertTitle,AlertDescription} from '@/components/ui/alert';
import rawSnapshot from '@/lib/surveillance.json';
import check from '@/lib/surveillance-check.json';
import {freshness} from '@/scripts/surveillance-core.mjs';
type Level='active'|'scheduled'|'imminent'|'attention'|'clear';
type StockSurveillance={id:string;name:string;level:Level;notices:{date:string;reason:string}[];trigger:{summary:string}|null;punishments:{announcedOn:string|null;start:string;end:string;period:string;reason:string;measure:string;detail:string;state:string}[]};
type Snapshot={asOf:string;checkedAt:string;status:string;sources:Record<string,{url:string;title:string;rows:number}>;records:StockSurveillance[]};
const snapshot=rawSnapshot as unknown as Snapshot;
const labels: {[key in Level]:string}={active:'處置中',scheduled:'已公告・即將處置',imminent:'可能觸發處置',attention:'公布注意',clear:'本次名單未列入'};
const links={notice:'https://www.twse.com.tw/zh/announcement/notice.html',notetrans:'https://www.twse.com.tw/zh/announcement/notetrans.html',punish:'https://www.twse.com.tw/zh/announcement/punish.html',rule:'https://twse-regulation.twse.com.tw/TW/law/DOC01.aspx?FLCODE=FL007225&FLNO=6'};
const formatTime=(value:string)=>new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value));
function useFreshness(){const [overdue,setOverdue]=useState(false);useEffect(()=>{const update=()=>{const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(check.checkedAt));setOverdue(freshness(day,Date.now())!=='current');};update();const timer=setInterval(update,60000);return()=>clearInterval(timer);},[]);return {overdue,failed:String(check.status)!=='verified'};}
export function SurveillanceBanner(){const {overdue,failed}=useFreshness();const alerts=snapshot.records.filter(r=>r.level!=='clear');return <Alert className={'surveillance-banner '+(failed||overdue?'uncertain':alerts.length?'warning':'neutral')} role="status"><BellRing size={20}/><AlertTitle>{failed?'處置資料待查核':overdue?'等待新一輪處置狀態更新':alerts.length?'交易警示':'注意／處置監測'}</AlertTitle><AlertDescription>{alerts.length?alerts.map(r=>`${r.name}：${labels[r.level]}`).join('；'):'追蹤股票均未列入本次查核的官方名單。'}<span> 官方資料 {snapshot.asOf} · 週一至週五 18:00 查核</span><a href="#surveillance">查看觸發條件與公告 <ArrowUpRight size={15}/></a></AlertDescription></Alert>}
export default function SurveillancePanel(){const {overdue,failed}=useFreshness();return <section id="surveillance" className="surveillance panel" aria-labelledby="surveillance-title"><div className="section-title"><div><span className="eyebrow">TRADING ALERTS</span><h2 id="surveillance-title"><ShieldAlert size={23}/>注意與處置警示</h2></div><span className="surveillance-time"><Clock3 size={15}/>查核 {formatTime(snapshot.checkedAt)}（台北）</span></div><p className="surveillance-intro">依證交所三份官方名單，分開追蹤「公布注意」、「可能達處置標準」及「已公告處置」。資料日期：{snapshot.asOf}。</p>{(failed||overdue)&&<Alert className="surveillance-stale" role="status"><AlertTitle>{failed?'本次查核未完成':'尚未取得新一輪查核結果'}</AlertTitle><AlertDescription>以下保留 {snapshot.asOf} 已確認資料，不能視為目前已解除警示。請同時查閱證交所最新公告。</AlertDescription></Alert>}
<div className="surveillance-grid">{snapshot.records.map(r=><article key={r.id} className={'surveillance-stock '+r.level}><div className="surveillance-stock-heading"><h3>{r.name}<span>{r.id}.TW</span></h3><span className={'surveillance-badge '+r.level}>{labels[r.level]}</span></div><dl className="surveillance-status"><div><dt>處置公告</dt><dd>{r.punishments.some(p=>p.state==='active')?'處置期間內':r.punishments.some(p=>p.state==='scheduled')?'已公告待生效':'本次查核未列入'}</dd></div><div><dt>當日注意</dt><dd>{r.notices.length?'已列入官方名單':'本次名單未列入'}</dd></div><div><dt>處置觸發提醒</dt><dd>{r.trigger?'已列入官方預警名單':'本次名單未列入'}</dd></div></dl>{r.trigger&&<div className="surveillance-trigger"><b>次一營業日需留意</b><p>{r.trigger.summary}。</p><p>若次一營業日再被公布納入處置計算的注意資訊，可能達處置標準。是否處置以當日正式公告為準。</p></div>}{r.punishments.map((p,i)=><div className="surveillance-punishment" key={p.start+i}><b>{p.measure} · {p.state==='scheduled'?'即將開始':p.state==='active'?'處置中':'已到期'}</b><p>公告：{p.announcedOn||'依原公告'}<br/>期間：{p.start} 至 {p.end}</p><p>{p.reason}</p><details><summary>查看官方處置措施</summary><p className="official-detail">{p.detail}</p></details></div>)}{r.notices.length>0&&<details className="surveillance-notices"><summary>查看注意原因（{r.notices.length}）</summary>{r.notices.map((notice,i)=><p key={i}><b>{notice.date}</b><br/>{notice.reason}</p>)}</details>}{r.level==='clear'&&<p className="surveillance-clear">本次查核未發現官方注意、處置或累計次數預警；未列入不代表沒有交易風險。</p>}<div className="surveillance-links">{(['notice','notetrans','punish'] as const).map(key=><a key={key} href={snapshot.sources[key].url.replace('response=json','response=html')} target="_blank" rel="noreferrer">{key==='notice'?'注意名單':key==='notetrans'?'觸發預警':'處置公告'}<ArrowUpRight size={14}/></a>)}</div></article>)}</div>
<details className="surveillance-rules"><summary>哪些情況可能觸發處置？</summary><div className="surveillance-rule-grid"><div><b>連續 3 個營業日</b><p>依第 4 條第 1 項第 1 款公布注意。</p></div><div><b>連續 5 日／10 日內 6 日／30 日內 12 日</b><p>依第 4 條第 1 項第 1 至 8 款公布注意；計算採營業日，並受排除規定影響。</p></div></div><p>頁面觸發提醒直接採證交所「可能達處置標準」名單；不以漲跌幅或全部注意次數自行預測。證交所亦可依其他規定或會議決議處置，個案期間與撮合方式以原公告為準。</p><a href={links.rule} target="_blank" rel="noreferrer">查閱現行作業要點第 6 條 ↗</a></details>
<p className="surveillance-footer">從 9/8 起週一至週五 18:00 偵測新增注意、處置、期間與措施變更及警示解除；查核完成後同步網站並提示。頁面為定時查核結果，非盤中即時警報；休市或資料未更新時保留前次有效資料。</p></section>}
