'use client';
import {useState, useEffect} from 'react';
import {flushSync} from 'react-dom';
import {registerValuationTool} from '@/lib/valuation';
import {ArrowUpRight, ArrowRight, ChartNoAxesCombined, BookOpen, Info, Layers2} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Slider} from '@/components/ui/slider';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import {stocks,sources} from '@/lib/research';
import SurveillancePanel,{SurveillanceBanner} from '@/components/surveillance-panel';
import ImportantChanges from '@/components/important-changes';
import {Quote,QuarterOverview,CompanyBrief} from '@/components/dashboard-charts';
import market from '@/lib/market-snapshot.json';
import {STOCK_CONFIG,stockConfig} from '@/lib/watchlist.mjs';
import {UpdateSchedule,SessionMarket,MarginPanel} from '@/components/market-session';
const n=(v:number|null|undefined,d=2)=>typeof v!=='number'||!Number.isFinite(v)?'待確認':v.toLocaleString('zh-TW',{minimumFractionDigits:d,maximumFractionDigits:d});
type Stock=typeof stocks[number];
function Cite({id}:{id:keyof typeof sources}){return <a className="cite" target="_blank" rel="noreferrer" href={sources[id].url}>{sources[id].label} ↗</a>}
function Comparison(){const rows=[['營業收入',...stocks.map(s=>n(s.revenue/100000)+' 億元')],['毛利率',...stocks.map(s=>n(s.gross/s.revenue*100)+'%')],['營業利益率',...stocks.map(s=>n(s.operating/s.revenue*100)+'%')],['歸屬母公司淨利',...stocks.map(s=>n(s.profit/100000)+' 億元')],['每股盈餘 EPS',...stocks.map(s=>n(s.eps)+' 元')],['每股淨值',...stocks.map(s=>n(s.bvps)+' 元')],['負債占資產',...stocks.map(s=>n(s.liabilities/s.assets*100)+'%')],['流動比率',...stocks.map(s=>n(s.currentAssets/s.currentLiabilities*100)+'%')]];
return <div className="comparison"><section className="panel"><div className="section-title"><div><span className="eyebrow">FUNDAMENTALS</span><h2>先看獲利，再看價格</h2></div><span className="period">{market.stocks.map(s=>s.name+" "+s.quarters.at(-1)?.period).join(" / ")}</span></div><Table className="data-table"><TableHeader><TableRow><TableHead>財務指標</TableHead>{stocks.map(s=><TableHead key={s.id}>{s.name} {s.id}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r[0]}>{r.map((v,i)=><TableCell key={i}>{v}</TableCell>)}</TableRow>)}</TableBody></Table><p className="footnote">損益為截至各股標示季度的年初累計；資產負債採同期期末。單季轉折另見季度獲利區塊。<Cite id="income"/> <Cite id="balance"/></p></section><section className="panel momentum"><span className="eyebrow">REVENUE MOMENTUM</span><h2>成長動能，正在分岔</h2><p className="muted">各公司最新已核對月份 · 營收年增率</p><div className="growths">{stocks.map(s=><div className="growth" key={s.id}><div><b>{s.name} <small>{market.stocks.find(m=>m.id===s.id)?.monthly.period}</small></b><strong>{s.yoy>0?'+':''}{n(s.yoy)}%</strong></div><div className="track"><span style={{width:Math.min(100,Math.abs(s.yoy)/Math.max(40,...stocks.map(s=>Math.abs(s.yoy)))*100)+'%',background:s.yoy>0?'#5477e9':'#6e91aa'}}/></div><p>年初至該月累計年增 <b>{s.ytdYoy>0?'+':''}{n(s.ytdYoy)}%</b> <a className="cite" href={market.stocks.find(m=>m.id===s.id)?.monthly.source.url} target="_blank" rel="noreferrer">來源 ↗</a></p></div>)}</div><div className="insight"><Info size={18}/><p>鼎元觀察成長延續性；富采與友達著重產品組合與本業獲利修復。單月成長不等於中長期獲利已改善。</p></div><p className="footnote">條長表示增減幅度的絕對值。各股月份依最新官方揭露分別列示。<Cite id="revenue"/></p></section></div>}
function Detail({s}:{s:Stock}){return <div className="detail"><section className="panel"><span className="eyebrow">EVIDENCE & ANALYSIS</span><h2>支撐判斷的核心證據</h2>{s.findings.map((f,i)=><article className="finding" key={f.title}><span>0{i+1}</span><div><h3>{f.title}</h3><p>{f.body}</p><Cite id={f.source as keyof typeof sources}/></div></article>)}</section><aside className="panel"><span className="eyebrow">WHAT TO WATCH</span><h2>下一次，驗證這些事</h2><p className="muted">研究條件，並非自動買賣訊號</p>{s.watch.map((w,i)=><div className="watch" key={w}><span>{i+1}</span><p>{w}</p></div>)}<div className="insight conclusion"><Info size={19}/><p>{s.conclusion}</p></div></aside></div>}
export default function Home(){const [tab,setTab]=useState('compare');const [selected,setSelected]=useState('2426');const [multiple,setMultiple]=useState(30);const s=stocks.find(s=>s.id===selected)!;const implied=s.price/multiple;
useEffect(()=>{try{const saved=sessionStorage.getItem('research-tab');if(saved&&['compare',...stocks.map(s=>s.id)].includes(saved))setTab(saved);}catch{}},[]);
useEffect(()=>{try{sessionStorage.setItem('research-tab',tab);}catch{}},[tab]);
useEffect(() => registerValuationTool((stockId, pe) => {
  flushSync(() => { setSelected(stockId); setMultiple(pe); });
}), []);
return <><header className="topbar"><a className="brand" href="#"><span><ChartNoAxesCombined size={23}/></span><b>台股股票研究</b><small>STOCK RESEARCH</small></a><div className="header-meta"><span>個人研究室</span><b><i/>研究基準 {market.asOf}</b></div></header><main><div className="page-title"><div><span className="eyebrow">TAIWAN EQUITY / 01</span><h1>台股股票研究</h1><p>鼎元 × 富采 × 友達 <span>·</span> 中長期基本面研究</p></div><a href="#sources" className="outline-link"><BookOpen size={17}/>資料與研究方法<ArrowUpRight size={16}/></a></div><div className="note"><Layers2 size={17}/><span><b>本期觀察</b> 營運改善不等於價格便宜。把成長假設，換成需要實現的獲利。</span><small>{market.stocks[0].quote.tradingDate} 收盤 · 非即時行情</small></div>
<UpdateSchedule/>
<SurveillanceBanner/>
<Tabs value={tab} onValueChange={v=>setTab(String(v))}><div className="tab-heading"><TabsList className="main-tabs"><TabsTrigger value="compare">三股比較<small>價格 · 財務 · 異動</small></TabsTrigger>{STOCK_CONFIG.map(s=><TabsTrigger key={s.id} value={s.id}>{s.name} {s.id}<small>{s.tabNote}</small></TabsTrigger>)}</TabsList><span>追蹤 {stocks.length} 家公司</span></div><SessionMarket stockId={tab==="compare"?"all":tab}/><div className={"quotes "+(tab!=="compare"?"single":"")}>{stocks.filter(s=>tab==="compare"||s.id===tab).map(s=><Quote key={s.id} s={s} choose={tab==="compare"?()=>setTab(s.id):undefined}/>)}</div><ImportantChanges stockId={tab==="compare"?"all":tab}/><MarginPanel stockId={tab==="compare"?"all":tab}/><TabsContent value="compare"><QuarterOverview/><Comparison/></TabsContent>{stocks.map(s=><TabsContent key={s.id} value={s.id}><CompanyBrief s={s}/><QuarterOverview stockId={s.id}/><Detail s={s}/></TabsContent>)}</Tabs>
<SurveillancePanel/>
<section id="valuation" className="valuation"><div className="valuation-intro"><span className="eyebrow">VALUATION LAB</span><h2>這個股價，<br/>需要多少獲利支撐？</h2><p>調整你願意給的本益比，反推公司每年需要賺多少。這是情境試算，並非獲利預測。</p><small>所需年 EPS = 收盤價 ÷ 假設本益比</small></div><div className="controls"><Tabs value={selected} onValueChange={v=>{setSelected(String(v));setMultiple(stockConfig(v).defaultPe)}}><TabsList className="stock-selector">{STOCK_CONFIG.map(s=><TabsTrigger key={s.id} value={s.id}>{s.name} {s.id}</TabsTrigger>)}</TabsList></Tabs><div className="slider-label"><label id="pe-label">假設本益比</label><b>{multiple}<small> 倍</small></b></div><Slider aria-labelledby="pe-label" value={[multiple]} min={10} max={60} step={1} onValueChange={v=>setMultiple(Array.isArray(v)?v[0]:v)}/><div className="scale"><span>10 倍</span><span>35 倍</span><span>60 倍</span></div><p>10–60 倍僅為試算範圍，未採同業或歷史估值分位；預設值不代表合理倍數。</p></div><div className="result" aria-live="polite" aria-atomic="true"><span>所需正常化年 EPS</span><strong>{n(implied)}<small> 元</small></strong><p>相當於期末淨值報酬約 <b>{n(implied/s.bvps*100)}%</b></p><div className="result-context"><span>證交所近四季 EPS 約</span><b>{typeof s.pe==='number'&&s.pe>0?n(s.price/s.pe):'不適用／待確認'} 元</b></div><div className="result-context"><span>所需 EPS / 近四季 EPS</span><b>{typeof s.pe==='number'&&s.pe>0?n(s.pe/multiple,1):'不適用／待確認'} 倍</b></div><small className="caveat">近四季 EPS 由官方本益比反推，含四捨五入。期末淨值報酬為簡化指標，非採平均權益計算的財報 ROE。</small></div></section>
<section className="takeaways"><div><span className="eyebrow">RESEARCH TAKEAWAYS</span><h2>各自的投資命題</h2></div>{stocks.map((s,i)=><article key={s.id}><span className={'company-tag '+stockConfig(s.id).theme}>{s.id} {s.name}</span><h3>{s.takeawayTitle}</h3><p>{s.takeaway}</p><button onClick={()=>{setTab(s.id);document.querySelector('.tab-heading')?.scrollIntoView({behavior:'smooth'})}}>閱讀研究重點<ArrowRight size={16}/></button></article>)}</section>
<section id="sources" className="sources"><div><span className="eyebrow">SOURCES & METHODOLOGY</span><h2>每個判斷，都有出處。</h2><p>研究基準 {market.asOf}（台北）。估值行情採證交所正式收盤；季報採各股標示的最新已核對季度，月營收採各公司最新已核對月份。頁面保留各資料所屬日期；從 9/8 起週一至週五 09:00–13:30 每半小時擷取行情，18:00 查核收盤研究與處置，新增注意／處置狀態亦納入每日變化偵測。</p><p>本益比與殖利率採證交所公布值；殖利率基於已公布股利，非未來配息承諾。現金流的資料精度及來源在個股分析中另行標註。</p><p className="disclaimer">本站為公開資料研究與假設試算，不包含個人持股或風險承受度評估。</p></div><div className="source-list">{Object.entries(sources).map(([id,s],i)=><a key={id} target="_blank" rel="noreferrer" href={s.url}><span>{String(i+1).padStart(2,'0')}</span><div><b>{s.label}</b><small>{s.detail}</small></div><ArrowUpRight size={16}/></a>)}</div></section></main><footer><span>台股股票研究 / 以證據形成判斷</span><span>TWSE 2426 · 3714 · 2409 / 2026.09</span></footer></>}

